### ISSUE TITLE
Make function-local variables possible

### ISSUE THREAD

**Issue by kid2407** [zz-roba/UdonPieCompiler#12] opened 2020-02-07 10:07 UTC
I would appreciate it if you could use the same variable names in functions, e.g. in a calculator. Currently, the following will give you an error on compile time:
```python
def _start():
    a = 5
    b = 7
    c = add(a, b)

    UnityEngineDebug.Log(SystemObject("Result: " + SystemConvert.ToString(c)))


def add(a: SystemInt32, b: SystemInt32) -> SystemInt32:
    return a + b
```
> Error: add_var: a is already registered.

Since the variables are only used inside the function, a way to realize this may be to prefix the variable names in the signature and inside the function with the function name.

**Comment by orels1** [comment] 2020-02-07 16:42
hmm, how do you suggest marking the variable file-scoped again though?
While it would be great to have function scoped vars (especially for things like `onTriggerEnter/Exit` params and so on) - having file-scoped vars is also a common occurance without marking them as global (so the user doesnt see them).

since you'll be using same names in differrent functions there is no way to tell if the variable should be global or function-scoped, so all of them will have to be made function scoped, which will instantly break existing code, and generally be pretty awkward as all the global variables will have to be defined as `global` and that way - displayed to the user. 

It's pretty common to have an `init` function, that defines a bunch of initial values on start that you then work with inside other functions.

Maybe smth like `_varName` notation for variables that are strictly meant to be function-scoped?

**Comment by kid2407** [comment] 2020-02-07 16:44
A "special" notation might be interesting, I didn't thought of the problem with global <=> local ^^
If not the "special notion", maybe a keyword like `local` would work if you want to insist on naming them the same, though I don't know how much more extra work for parsing / compiling that would be. That still would leave us with the problem in such a case:
```python
myvar = 20

def doStuff(myvar: SystemInt32) -> systemVoid:
    return = myvar * 2 # which myvar do i want?
   
```

**Comment by Foorack** [comment] 2020-02-07 17:01
How about using `this.` as in regular C#, and special-handling the situation whenever the parser finds a variable called "this"?

And internally they could be named something like `_<functionName>_<varName>` e.g `_doStuff_myvar` as to not accidentally collide with anything else.

Example:
```python
myvar= 20

def doStuff(myvar: SystemInt32) -> SystemVoid:
    return = this.myvar* 2
```

**Comment by Foorack** [comment] 2020-02-07 17:17
@orels1 A way to solve if a variable should be global or function-scoped would be to have any function parameter defined internally as `_<functionName>_<variableName>`, and then whenever a variable is accessed it would first use that prefixing to lookup if a variable exists, and if not then check global with just the normal name.

@kid2407 That would primarily be a case of not naming arguments the same as global variables. One method could be to implement a `self.`, and whenever a variable with exactly that name is matched it will be handled specially.

https://www.w3schools.com/python/python_scope.asp
The default python handling is:
> If you operate with the same variable name inside and outside of a function, Python will treat them as two separate variables, one available in the global scope (outside the function) and one available in the local scope (inside the function).
I.e. in standard python the following code will first print 200, then 300.
```python
x = 300

def myfunc():
  x = 200
  print(x)

myfunc()

print(x) ```

**Comment by orels1** [comment] 2020-02-08 06:53
Yeah i get the default python way. I think there is a bit of a confusion between what i'm discussing and what is actually being proposed.

I was thinking more of general proposal of all variables defined inside a function to be function-scoped. So... the python way :) If we're talking only the function arguments, then yeah, your proposal for lookup totally works. But if we're talking all variables  - we'll need something like `self` for sure, or otherwise there won't be a way to share variables initialized in `start` to other methods lik` update`.

**Comment by zz-roba** [comment] 2020-02-09 01:33
At first, I wanted to create a variable scope (C-like block scope)
using a variable table managed by the stack.
(But I didn't implement it because I wanted to make a game with UdonPie early. I'm sorry.)

It works as follows.
* Indent(enter block): push a new empty variable table onto the stack.
* Variable declaration: Add to the variable table at the top of the stack
* Resolve variables: Resolve variables from the top of the stack.
* Dedent(exit block): Pop the variable table off the stack.

Which variable scope is better ...

**Comment by zz-roba** [comment] 2020-02-11 04:07
I changed the scope of function arguments from global to inside functions.

Code example:
```py
def _start():
  a = 5
  b = 7
  c = add(a, b)
  UnityEngineDebug.Log(SystemObject("add result: " + SystemConvert.ToString(c))) # 12
  UnityEngineDebug.Log(SystemObject("a = " + SystemConvert.ToString(a))) # 5
  UnityEngineDebug.Log(SystemObject("b = " + SystemConvert.ToString(b))) # 7
  var_test(a, b)
  UnityEngineDebug.Log(SystemObject("a = " + SystemConvert.ToString(a))) # 5
  UnityEngineDebug.Log(SystemObject("b = " + SystemConvert.ToString(b))) # 7

def add(a: SystemInt32, b: SystemInt32) -> SystemInt32:
  return a + b

def var_test(a: SystemInt32, b:SystemInt32) -> SystemVoid:
  a = 10000
  b = 20000
  UnityEngineDebug.Log(SystemObject("a = " + SystemConvert.ToString(a))) # 10000
  UnityEngineDebug.Log(SystemObject("b = " + SystemConvert.ToString(b))) # 20000

```

**Comment by Foorack** [comment] 2020-02-11 08:48
@zz-roba Thank you **very** much for this, this will help a lot! 😊👍 

I suggest closing this as the issue is now resolved.

**Closed as completed** 2020-02-11 14:20 UTC
